<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Wireless Headphones',
                'slug' => 'wireless-headphones',
                'sku' => 'SKU-001',
                'description' => 'High-quality wireless headphones with noise cancellation',
                'price' => 199.99,
                'cost' => 120.00,
                'stock' => 50,
                'status' => 'active',
                'is_featured' => true,
                'is_visible' => true,
                'brand' => 'Sony',
                'category' => 'Electronics',
                'tags' => ['audio', 'wireless', 'premium'],
                'specifications' => ['Battery Life' => '30 hours', 'Bluetooth' => '5.0'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => 'Smart Watch Pro',
                'slug' => 'smart-watch-pro',
                'sku' => 'SKU-002',
                'description' => 'Advanced smartwatch with health tracking features',
                'price' => 299.99,
                'cost' => 180.00,
                'stock' => 30,
                'status' => 'active',
                'is_featured' => true,
                'is_visible' => true,
                'brand' => 'Apple',
                'category' => 'Electronics',
                'tags' => ['wearable', 'health', 'smart'],
                'specifications' => ['Display' => 'OLED', 'Water Resistant' => 'Yes'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => 'USB-C Cable',
                'slug' => 'usb-c-cable',
                'sku' => 'SKU-003',
                'description' => 'Durable USB-C charging cable',
                'price' => 19.99,
                'cost' => 8.00,
                'stock' => 200,
                'status' => 'active',
                'is_featured' => false,
                'is_visible' => true,
                'brand' => 'Anker',
                'category' => 'Electronics',
                'tags' => ['cable', 'usb-c', 'accessory'],
                'specifications' => ['Length' => '2 meters', 'Power' => '100W'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => 'Mechanical Keyboard',
                'slug' => 'mechanical-keyboard',
                'sku' => 'SKU-004',
                'description' => 'RGB mechanical keyboard with Cherry MX switches',
                'price' => 149.99,
                'cost' => 85.00,
                'stock' => 25,
                'status' => 'active',
                'is_featured' => true,
                'is_visible' => true,
                'brand' => 'Corsair',
                'category' => 'Electronics',
                'tags' => ['keyboard', 'gaming', 'rgb'],
                'specifications' => ['Switches' => 'Cherry MX Red', 'RGB' => 'Yes'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => 'Laptop Stand',
                'slug' => 'laptop-stand',
                'sku' => 'SKU-005',
                'description' => 'Adjustable aluminum laptop stand',
                'price' => 49.99,
                'cost' => 25.00,
                'stock' => 75,
                'status' => 'active',
                'is_featured' => false,
                'is_visible' => true,
                'brand' => 'Generic',
                'category' => 'Home & Garden',
                'tags' => ['laptop', 'desk', 'ergonomic'],
                'specifications' => ['Material' => 'Aluminum', 'Adjustable' => 'Yes'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => '4K Monitor',
                'slug' => '4k-monitor',
                'sku' => 'SKU-006',
                'description' => '27-inch 4K UHD monitor with HDR support',
                'price' => 399.99,
                'cost' => 250.00,
                'stock' => 15,
                'status' => 'active',
                'is_featured' => true,
                'is_visible' => true,
                'brand' => 'LG',
                'category' => 'Electronics',
                'tags' => ['monitor', '4k', 'display'],
                'specifications' => ['Resolution' => '3840x2160', 'HDR' => 'Yes'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => 'Wireless Mouse',
                'slug' => 'wireless-mouse',
                'sku' => 'SKU-007',
                'description' => 'Ergonomic wireless mouse with precision tracking',
                'price' => 39.99,
                'cost' => 18.00,
                'stock' => 100,
                'status' => 'active',
                'is_featured' => false,
                'is_visible' => true,
                'brand' => 'Logitech',
                'category' => 'Electronics',
                'tags' => ['mouse', 'wireless', 'ergonomic'],
                'specifications' => ['DPI' => '4000', 'Battery' => '6 months'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => 'External SSD',
                'slug' => 'external-ssd',
                'sku' => 'SKU-008',
                'description' => '1TB portable external SSD with USB 3.2',
                'price' => 129.99,
                'cost' => 75.00,
                'stock' => 40,
                'status' => 'active',
                'is_featured' => false,
                'is_visible' => true,
                'brand' => 'Samsung',
                'category' => 'Electronics',
                'tags' => ['storage', 'ssd', 'portable'],
                'specifications' => ['Capacity' => '1TB', 'Speed' => '1050 MB/s'],
                'published_at' => now(),
                'user_id' => 1,
            ],
            [
                'name' => 'Webcam HD',
                'slug' => 'webcam-hd',
                'sku' => 'SKU-009',
                'description' => '1080p HD webcam with auto-focus',
                'price' => 79.99,
                'cost' => 42.00,
                'stock' => 60,
                'status' => 'draft',
                'is_featured' => false,
                'is_visible' => false,
                'brand' => 'Logitech',
                'category' => 'Electronics',
                'tags' => ['webcam', 'video', 'streaming'],
                'specifications' => ['Resolution' => '1080p', 'Auto-focus' => 'Yes'],
                'published_at' => null,
                'user_id' => 1,
            ],
            [
                'name' => 'Desk Lamp LED',
                'slug' => 'desk-lamp-led',
                'sku' => 'SKU-010',
                'description' => 'Adjustable LED desk lamp with touch control',
                'price' => 34.99,
                'cost' => 15.00,
                'stock' => 80,
                'status' => 'active',
                'is_featured' => false,
                'is_visible' => true,
                'brand' => 'Generic',
                'category' => 'Home & Garden',
                'tags' => ['lamp', 'led', 'desk'],
                'specifications' => ['Brightness Levels' => '5', 'Color Temperature' => 'Adjustable'],
                'published_at' => now(),
                'user_id' => 1,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
